In [1]:
from absenteeism_predictor import *

In [2]:
df=pd.read_csv("D:/absenteeism_project/Absenteeism_new_data.csv")
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0

In [3]:
model = absenteeism_model("model","scaler")

In [4]:
model.load_and_clean_data("D:/absenteeism_project/Absenteeism_new_data.csv")

In [5]:
model.predicted_outputs()

,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month Values,Probability,Predictions
0,179,30,19,1,0,0,0,0.0,0,1,6,0.147242,0
1,361,28,27,0,1,4,1,0.0,0,0,6,0.894660,1
2,155,34,25,0,2,0,0,0.0,0,1,6,0.283018,0
3,179,40,22,1,2,0,0,0.0,0,1,6,0.239460,0
4,155,34,25,0,2,0,1,0.0,0,0,6,0.725578,1
5,225,28,24,0,1,2,1,0.0,0,0,6,0.732036,1
6,118,46,25,0,2,0,1,0.0,0,0,6,0.546092,1
7,179,30,19,1,0,0,0,0.0,0,1,6,0.147242,0
8,118,37,28,0,0,0,0,0.0,0,1,6,0.121597,0
9,118,37,28,0,0,0,1,0.0,0,0,6,0.481121,0
10,378,36,21,0,2,4,0,0.0,0,1,6,0.535769,1
11,118,50,31,0,1,0,0,0.0,1,0,6,0.580489,1
12,233,31,21,1,1,8,0,0.0,1,0,6,0.410061,0
13,179,30,19,1,0,0,0,0.0,0,1,6,0.147242,0
14,235,48,33,0,1,5,0,0.0,0,0,6,0.077260,0
15,268,33,25,1,0,0,0,0.0,0,0,6,0.188588,0
16,118,50,31,0,1,0,0,0.0,1,0,6,0.580489,1
17,179,30,19,1,0,0,1,0.0,0,0,6,0.536295,1
18,291,40,25,0,1,1,0,0.0,0,1,6,0.416837,0
19,179,30,19,1,0,0,1,0.0,0,0,7,0.542659,1
20,118,37,28,0,0,0,0,0.0,0,1,7,0.124360,0
21,233,31,21,1,1,8,0,0.0,0,1,7,0.074645,0
22,118,37,28,0,0,0,1,0.0,0,0,7,0.487519,0
23,118,37,28,0,0,0,1,0.0,0,0,7,0.487519,0
24,233,31,21,1,1,8,0,0.0,0,1,7,0.074645,0
25,235,43,38,0,1,0,0,0.0,0,1,7,0.512211,1
26,233,31,21,1,1,8,0,0.0,1,0,7,0.416272,0
27,228,58,22,0,2,1,1,0.0,0,0,7,0.627746,1
28,118,37,28,0,0,0,0,0.0,0,1,7,0.124360,0
29,228,58,22,0,2,1,1,0.0,0,0,7,0.627746,1
30,189,33,25,0,2,2,0,0.0,0,1,7,0.274379,0
31,118,37,28,0,0,0,0,0.0,0,1,7,0.124360,0
32,361,28,27,0,1,4,0,0.0,0,1,7,0.565381,1
33,225,28,24,0,1,2,0,0.0,0,1,7,0.294995,0
34,369,31,25,0,3,0,1,0.0,0,0,7,0.975351,1
35,289,33,30,0,2,1,1,0.0,0,0,7,0.923890,1
36,235,37,29,1,1,1,1,0.0,0,0,7,0.783108,1
37,118,40,34,0,1,8,0,0.0,0,0,7,0.017922,0
38,231,39,35,0,2,2,0,0.0,0,0,7,0.266749,0
39,179,53,25,0,1,1,0,0.0,0,0,7,0.057623,0

In [6]:
model.predicted_outputs().to_csv("Absenteeism_predictions.csv",index=False)